name: CI
on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  lint:
    name: Run Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Initialize terraform project
        run: terraform init

      - name: Format terraform files
        run: terraform fmt -check 

  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize terraform project
        run: terraform init

      - name: Validate Terraform
        run: terraform validate