name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      workspace:
        required: true
        type: string
        default: prod
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Destroy
        uses: dflook/terraform-destroy@v2
        with:
          workspace: ${{ github.event.inputs.workspace }}